# Day 16: Selecting Rows and Columns with loc and iloc

**Dataset:** `Titanic_Dataset.csv`

This notebook practices selecting rows and columns using Pandas `loc[]` and `iloc[]`, and
explores the difference between label-based and position-based selection, using real values
pulled directly from the Titanic dataset.

## 1. Import Libraries and Load the Dataset

In [1]:
import pandas as pd

# Load the dataset
df = pd.read_csv("../datasets/Titanic_Dataset.csv")

# Preview the data
df.head()

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**A note on the index**

By default, `df`'s row labels are just integers 0, 1, 2, ..., the same as their positions.
To make the difference between `loc[]` (label-based) and `iloc[]` (position-based) obvious,
this notebook also creates a second version of the DataFrame indexed by `PassengerId`
instead, so the row *labels* and row *positions* are no longer the same numbers.

In [2]:
df_by_id = df.set_index("PassengerId")
df_by_id.head()

,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
PassengerId,,,,,,,,,,,
1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

## 2. `loc[]` Examples: Label-Based Selection

`loc[]` selects using **labels**, whether it is the actual index value or column name, not its numeric
position.

**Example 1: Select a single row by its label (default integer index)**

In [3]:
print(df.loc[0])

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

**Example 2: Select a range of rows by label (both ends are included)**

In [4]:
df.loc[0:4]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Example 3: Select specific columns for every row**

In [5]:
df.loc[:, ["Name", "Age", "Survived"]].head()

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0

**Example 4: Select specific rows and specific columns together**

In [6]:
df.loc[0:3, ["Name", "Pclass", "Fare"]]

                                                Name  Pclass     Fare
0                            Braund, Mr. Owen Harris       3   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
2                             Heikkinen, Miss. Laina       3   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000

**Example 5: Select a row using a real, non-default label (`PassengerId`)**

In [7]:
# PassengerId 3 is Pclass 3 Passenger with different positions in the two DataFrames
print(df_by_id.loc[3])

Survived                         1
Pclass                           3
Name        Heikkinen, Miss. Laina
Sex                         female
Age                           26.0
SibSp                            0
Parch                            0
Ticket            STON/O2. 3101282
Fare                         7.925
Cabin                          NaN
Embarked                         S
Name: 3, dtype: object

**Example 6: Boolean filtering combined with `loc[]` to select rows and columns together**

In [8]:
df.loc[df["Age"] > 70, ["Name", "Age", "Survived"]]

                                     Name   Age  Survived
96              Goldschmidt, Mr. George B  71.0         0
116                  Connors, Mr. Patrick  70.5         0
493               Artagaveytia, Mr. Ramon  71.0         0
630  Barkworth, Mr. Algernon Henry Wilson  80.0         1
851                   Svensson, Mr. Johan  74.0         0

## 3. `iloc[]` Examples: Position-Based Selection

`iloc[]` selects using **integer positions**, counting from `0`, regardless of what the actual
row labels or column names are.

**Example 1: Select a single row by its position**

In [9]:
print(df.iloc[0])

PassengerId                          1
Survived                             0
Pclass                               3
Name           Braund, Mr. Owen Harris
Sex                               male
Age                               22.0
SibSp                                1
Parch                                0
Ticket                       A/5 21171
Fare                              7.25
Cabin                              NaN
Embarked                             S
Name: 0, dtype: object

**Example 2: Select a range of rows by position (the end position is NOT included)**

In [10]:
df.iloc[0:5]

,PassengerId,Survived,Pclass,Name,Sex,Age,SibSp,Parch,Ticket,Fare,Cabin,Embarked
0,1,0,3,"Braund, Mr. Owen Harris",male,22.0,1,0,A/5 21171,7.2500,NaN,S
1,2,1,1,"Cumings, Mrs. John Bradley (Florence Briggs Th...",female,38.0,1,0,PC 17599,71.2833,C85,C
2,3,1,3,"Heikkinen, Miss. Laina",female,26.0,0,0,STON/O2. 3101282,7.9250,NaN,S
3,4,1,1,"Futrelle, Mrs. Jacques Heath (Lily May Peel)",female,35.0,1,0,113803,53.1000,C123,S
4,5,0,3,"Allen, Mr. William Henry",male,35.0,0,0,373450,8.0500,NaN,S

**Example 3: Select specific columns by their position for every row**

In [11]:
df.iloc[:, [3, 5, 1]].head()   # Name, Age, Survived columns, by position

                                                Name   Age  Survived
0                            Braund, Mr. Owen Harris  22.0         0
1  Cumings, Mrs. John Bradley (Florence Briggs Th...  38.0         1
2                             Heikkinen, Miss. Laina  26.0         1
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)  35.0         1
4                           Allen, Mr. William Henry  35.0         0

**Example 4: Select specific rows and specific columns together, by position**

In [12]:
df.iloc[0:4, [3, 2, 9]]   # first 4 rows; Name, Pclass, Fare columns

                                                Name  Pclass     Fare
0                            Braund, Mr. Owen Harris       3   7.2500
1  Cumings, Mrs. John Bradley (Florence Briggs Th...       1  71.2833
2                             Heikkinen, Miss. Laina       3   7.9250
3       Futrelle, Mrs. Jacques Heath (Lily May Peel)       1  53.1000

**Example 5: Select a row from `df_by_id` by position (NOT by its `PassengerId` label)**

In [13]:
# This selects the 3rd row in the DataFrame's current order,
# whatever PassengerId that row happens to have.
print(df_by_id.iloc[2])

Survived                         1
Pclass                           3
Name        Heikkinen, Miss. Laina
Sex                         female
Age                           26.0
SibSp                            0
Parch                            0
Ticket            STON/O2. 3101282
Fare                         7.925
Cabin                          NaN
Embarked                         S
Name: 3, dtype: object

**Example 6: Select the last 3 rows and the first 2 columns using negative and positional indexing**

In [14]:
df.iloc[-3:, 0:2]

     PassengerId  Survived
888          889         0
889          890         1
890          891         0

## 4. Comparing `loc[]` and `iloc[]`

The clearest way to see the difference is to make the same request both ways on
`df_by_id`, where the row **labels** (`PassengerId`, starting at 1) and row **positions**
(starting at 0) are no longer the same numbers.

In [15]:
# loc[3] looks for the row LABELED PassengerId == 3
print("loc[3] (label-based):")
print(df_by_id.loc[3][["Name", "Age"]])

print()

# iloc[3] looks for the row at POSITION 3 (the 4th row, PassengerId == 4)
print("iloc[3] (position-based):")
print(df_by_id.iloc[3][["Name", "Age"]])

loc[3] (label-based):
Name    Heikkinen, Miss. Laina
Age                       26.0
Name: 3, dtype: object

iloc[3] (position-based):
Name    Futrelle, Mrs. Jacques Heath (Lily May Peel)
Age                                             35.0
Name: 4, dtype: object

**Another key difference: slice endpoints**

`loc[]` slices are **inclusive** of the end label. `iloc[]` slices are **exclusive** of the
end position, just like regular Python list slicing.

In [16]:
print("loc[0:4] includes rows 0, 1, 2, 3, AND 4:")
print(len(df.loc[0:4]), "rows")

print()

print("iloc[0:4] includes rows 0, 1, 2, 3 only (position 4 is excluded):")
print(len(df.iloc[0:4]), "rows")

loc[0:4] includes rows 0, 1, 2, 3, AND 4:
5 rows

iloc[0:4] includes rows 0, 1, 2, 3 only (position 4 is excluded):
4 rows

| | `loc[]` | `iloc[]` |
|---|---|---|
| Selects by | Label (index value / column name) | Integer position (starting at 0) |
| Slice `0:4` includes | Everything through label `4` (inclusive) | Positions 0, 1, 2, 3 only (exclusive of 4) |
| Works if index isn't 0, 1, 2... | Yes, it uses the actual labels | Yes, the position is unaffected by the labels |
| Column selection | By column name | By column position |

## Outcome

This notebook practiced selecting rows and columns from the `Titanic_Dataset.csv` file using
both `loc[]` and `iloc[]`. With `loc[]`, I selected single rows and inclusive ranges by label,
specific columns by name, combined row-and-column selections, a row using a real non-default
label (`PassengerId`), and rows filtered by a boolean condition. With `iloc[]`, I selected
single rows and exclusive ranges by position, specific columns by their numeric position,
combined row-and-column selections by position, and rows using negative positional indexing.
Setting `PassengerId` as the index made the difference between the two very concrete: calling
`loc[3]` and `iloc[3]` on the same DataFrame returned two different passengers, since one
looks up a label and the other looks up a position. I also confirmed that `loc[]` slices
include their end label while `iloc[]` slices exclude their end position, which is an easy
mistake to make if the two are confused.